package com.myexpense.tracker.utils

/** A currency the user can pick during onboarding setup. */
data class CurrencyInfo(
    val code: String,
    val name: String,
    val symbol: String,
)

/** Top 20 world currencies, INR first (the app's default). */
val TopCurrencies: List<CurrencyInfo> = listOf(
    CurrencyInfo("INR", "Indian Rupee", "₹"),
    CurrencyInfo("USD", "US Dollar", "$"),
    CurrencyInfo("EUR", "Euro", "€"),
    CurrencyInfo("GBP", "British Pound", "£"),
    CurrencyInfo("JPY", "Japanese Yen", "¥"),
    CurrencyInfo("CNY", "Chinese Yuan", "¥"),
    CurrencyInfo("AUD", "Australian Dollar", "A$"),
    CurrencyInfo("CAD", "Canadian Dollar", "C$"),
    CurrencyInfo("CHF", "Swiss Franc", "CHF"),
    CurrencyInfo("SGD", "Singapore Dollar", "S$"),
    CurrencyInfo("HKD", "Hong Kong Dollar", "HK$"),
    CurrencyInfo("KRW", "South Korean Won", "₩"),
    CurrencyInfo("AED", "UAE Dirham", "د.إ"),
    CurrencyInfo("SAR", "Saudi Riyal", "﷼"),
    CurrencyInfo("RUB", "Russian Ruble", "₽"),
    CurrencyInfo("BRL", "Brazilian Real", "R$"),
    CurrencyInfo("ZAR", "South African Rand", "R"),
    CurrencyInfo("TRY", "Turkish Lira", "₺"),
    CurrencyInfo("MXN", "Mexican Peso", "MX$"),
    CurrencyInfo("NZD", "New Zealand Dollar", "NZ$"),
)

/** Extended list (50+) for the account currency picker. */
val AllCurrencies: List<CurrencyInfo> = TopCurrencies + listOf(
    CurrencyInfo("AFN", "Afghan Afghani", "؋"),
    CurrencyInfo("BDT", "Bangladeshi Taka", "৳"),
    CurrencyInfo("BGN", "Bulgarian Lev", "лв"),
    CurrencyInfo("BHD", "Bahraini Dinar", ".د.ب"),
    CurrencyInfo("CLP", "Chilean Peso", "$"),
    CurrencyInfo("COP", "Colombian Peso", "$"),
    CurrencyInfo("CZK", "Czech Koruna", "Kč"),
    CurrencyInfo("DKK", "Danish Krone", "kr"),
    CurrencyInfo("EGP", "Egyptian Pound", "E£"),
    CurrencyInfo("HUF", "Hungarian Forint", "Ft"),
    CurrencyInfo("IDR", "Indonesian Rupiah", "Rp"),
    CurrencyInfo("ILS", "Israeli Shekel", "₪"),
    CurrencyInfo("ISK", "Icelandic Króna", "kr"),
    CurrencyInfo("KES", "Kenyan Shilling", "KSh"),
    CurrencyInfo("KWD", "Kuwaiti Dinar", "د.ك"),
    CurrencyInfo("LKR", "Sri Lankan Rupee", "Rs"),
    CurrencyInfo("MAD", "Moroccan Dirham", "د.م."),
    CurrencyInfo("MMK", "Myanmar Kyat", "K"),
    CurrencyInfo("MYR", "Malaysian Ringgit", "RM"),
    CurrencyInfo("NGN", "Nigerian Naira", "₦"),
    CurrencyInfo("NOK", "Norwegian Krone", "kr"),
    CurrencyInfo("NPR", "Nepalese Rupee", "रू"),
    CurrencyInfo("PHP", "Philippine Peso", "₱"),
    CurrencyInfo("PKR", "Pakistani Rupee", "₨"),
    CurrencyInfo("PLN", "Polish Złoty", "zł"),
    CurrencyInfo("QAR", "Qatari Riyal", "﷼"),
    CurrencyInfo("RON", "Romanian Leu", "lei"),
    CurrencyInfo("RSD", "Serbian Dinar", "дин"),
    CurrencyInfo("SEK", "Swedish Krona", "kr"),
    CurrencyInfo("THB", "Thai Baht", "฿"),
    CurrencyInfo("TWD", "New Taiwan Dollar", "NT$"),
    CurrencyInfo("UAH", "Ukrainian Hryvnia", "₴"),
    CurrencyInfo("UGX", "Ugandan Shilling", "USh"),
    CurrencyInfo("VND", "Vietnamese Đồng", "₫"),
    CurrencyInfo("XAF", "Central African CFA", "FCFA"),
    CurrencyInfo("XOF", "West African CFA", "CFA"),
    CurrencyInfo("ARS", "Argentine Peso", "$"),
    CurrencyInfo("PEN", "Peruvian Sol", "S/"),
    CurrencyInfo("VES", "Venezuelan Bolívar", "Bs"),
)
