package com.myexpense.tracker.utils

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.ui.graphics.vector.ImageVector

/**
 * Maps icon names (stored in the database) to Material icons.
 * Only icons listed here are available when picking an icon.
 */
object IconMap {

    val all: Map<String, ImageVector> = linkedMapOf(
        "restaurant" to Icons.Filled.Restaurant,
        "shopping_cart" to Icons.Filled.ShoppingCart,
        "shopping_bag" to Icons.Filled.ShoppingBag,
        "directions_bus" to Icons.Filled.DirectionsBus,
        "local_gas_station" to Icons.Filled.LocalGasStation,
        "directions_car" to Icons.Filled.DirectionsCar,
        "flight" to Icons.Filled.Flight,
        "hotel" to Icons.Filled.Hotel,
        "home" to Icons.Filled.Home,
        "bolt" to Icons.Filled.Bolt,
        "water_drop" to Icons.Filled.WaterDrop,
        "wifi" to Icons.Filled.Wifi,
        "phone_android" to Icons.Filled.PhoneAndroid,
        "movie" to Icons.Filled.Movie,
        "sports_esports" to Icons.Filled.SportsEsports,
        "music_note" to Icons.Filled.MusicNote,
        "menu_book" to Icons.Filled.MenuBook,
        "school" to Icons.Filled.School,
        "fitness_center" to Icons.Filled.FitnessCenter,
        "medical_services" to Icons.Filled.MedicalServices,
        "favorite" to Icons.Filled.Favorite,
        "pets" to Icons.Filled.Pets,
        "child_care" to Icons.Filled.ChildCare,
        "card_giftcard" to Icons.Filled.CardGiftcard,
        "redeem" to Icons.Filled.Redeem,
        "celebration" to Icons.Filled.Celebration,
        "payments" to Icons.Filled.Payments,
        "account_balance" to Icons.Filled.AccountBalance,
        "account_balance_wallet" to Icons.Filled.AccountBalanceWallet,
        "savings" to Icons.Filled.Savings,
        "credit_card" to Icons.Filled.CreditCard,
        "currency_exchange" to Icons.Filled.CurrencyExchange,
        "trending_up" to Icons.Filled.TrendingUp,
        "trending_down" to Icons.Filled.TrendingDown,
        "show_chart" to Icons.Filled.ShowChart,
        "pie_chart" to Icons.Filled.PieChart,
        "bar_chart" to Icons.Filled.BarChart,
        "work" to Icons.Filled.Work,
        "business" to Icons.Filled.Business,
        "laptop" to Icons.Filled.Laptop,
        "computer" to Icons.Filled.Computer,
        "brush" to Icons.Filled.Brush,
        "build" to Icons.Filled.Build,
        "handyman" to Icons.Filled.Handyman,
        "local_laundry_service" to Icons.Filled.LocalLaundryService,
        "checkroom" to Icons.Filled.Checkroom,
        "dry_cleaning" to Icons.Filled.DryCleaning,
        "pregnant_woman" to Icons.Filled.PregnantWoman,
        "elderly" to Icons.Filled.Elderly,
        "cake" to Icons.Filled.Cake,
        "local_cafe" to Icons.Filled.LocalCafe,
        "liquor" to Icons.Filled.Liquor,
        "local_bar" to Icons.Filled.LocalBar,
        "fastfood" to Icons.Filled.Fastfood,
        "icecream" to Icons.Filled.Icecream,
        "bakery_dining" to Icons.Filled.BakeryDining,
        "soup_kitchen" to Icons.Filled.SoupKitchen,
        "kebab_dining" to Icons.Filled.KebabDining,
        "ramen_dining" to Icons.Filled.RamenDining,
        "set_meal" to Icons.Filled.SetMeal,
        "delivery_dining" to Icons.Filled.DeliveryDining,
        "takeout_dining" to Icons.Filled.TakeoutDining,
        "local_pizza" to Icons.Filled.LocalPizza,
        "local_dining" to Icons.Filled.LocalDining,
        "local_mall" to Icons.Filled.LocalMall,
        "local_pharmacy" to Icons.Filled.LocalPharmacy,
        "local_hospital" to Icons.Filled.LocalHospital,
        "local_taxi" to Icons.Filled.LocalTaxi,
        "local_shipping" to Icons.Filled.LocalShipping,
        "train" to Icons.Filled.Train,
        "subway" to Icons.Filled.Subway,
        "two_wheeler" to Icons.Filled.TwoWheeler,
        "pedal_bike" to Icons.Filled.PedalBike,
        "electric_car" to Icons.Filled.ElectricCar,
        "ev_station" to Icons.Filled.EvStation,
        "commute" to Icons.Filled.Commute,
        "airport_shuttle" to Icons.Filled.AirportShuttle,
        "luggage" to Icons.Filled.Luggage,
        "hiking" to Icons.Filled.Hiking,
        "kayaking" to Icons.Filled.Kayaking,
        "surfing" to Icons.Filled.Surfing,
        "camping" to Icons.Filled.Camping,
        "photo_camera" to Icons.Filled.PhotoCamera,
        "smartphone" to Icons.Filled.Smartphone,
        "tv" to Icons.Filled.Tv,
        "headphones" to Icons.Filled.Headphones,
        "speaker" to Icons.Filled.Speaker,
        "watch" to Icons.Filled.Watch,
        "videogame_asset" to Icons.Filled.VideogameAsset,
        "sports_basketball" to Icons.Filled.SportsBasketball,
        "sports_soccer" to Icons.Filled.SportsSoccer,
        "sports_tennis" to Icons.Filled.SportsTennis,
        "sports_cricket" to Icons.Filled.SportsCricket,
        "fitness_center2" to Icons.Filled.FitnessCenter,
        "self_improvement" to Icons.Filled.SelfImprovement,
        "spa" to Icons.Filled.Spa,
        "smoke_free" to Icons.Filled.SmokeFree,
        "volunteer_activism" to Icons.Filled.VolunteerActivism,
        "handshake" to Icons.Filled.Handshake,
        "diversity_3" to Icons.Filled.Diversity3,
        "groups" to Icons.Filled.Groups,
        "family_restroom" to Icons.Filled.FamilyRestroom,
        "pets2" to Icons.Filled.Pets,
        "agriculture" to Icons.Filled.Agriculture,
        "forest" to Icons.Filled.Forest,
        "park" to Icons.Filled.Park,
        "eco" to Icons.Filled.Eco,
        "recycling" to Icons.Filled.Recycling,
        "cleaning_services" to Icons.Filled.CleaningServices,
        "plumbing" to Icons.Filled.Plumbing,
        "electrical_services" to Icons.Filled.ElectricalServices,
        "car_repair" to Icons.Filled.CarRepair,
        "payments2" to Icons.Filled.Payments,
        "request_quote" to Icons.Filled.RequestQuote,
        "price_check" to Icons.Filled.PriceCheck,
        "sell" to Icons.Filled.Sell,
        "attach_money" to Icons.Filled.AttachMoney,
        "currency_rupee" to Icons.Filled.CurrencyRupee,
        "euro" to Icons.Filled.Euro,
        "add_card" to Icons.Filled.AddCard,
        "account_balance2" to Icons.Filled.AccountBalance,
        "savings2" to Icons.Filled.Savings,
        "wallet" to Icons.Filled.Wallet,
        "category" to Icons.Filled.Category,
        "add_circle" to Icons.Filled.AddCircle,
        "remove_circle" to Icons.Filled.RemoveCircle,
        "star" to Icons.Filled.Star,
        "auto_awesome" to Icons.Filled.AutoAwesome,
        "emoji_events" to Icons.Filled.EmojiEvents,
        "workspace_premium" to Icons.Filled.WorkspacePremium,
        "verified" to Icons.Filled.Verified,
        "military_tech" to Icons.Filled.MilitaryTech,
        "diamond" to Icons.Filled.Diamond,
    )

    fun get(name: String?): ImageVector = all[name] ?: Icons.Filled.Category
}
